language: php

php:
  - 5.6
  - hhvm
  - nightly

before_install:
  - pyrus install pear/PHP_CodeSniffer-2.1.0
  - phpenv rehash
  - composer self-update
  - composer install

script:
  - php vendor/scabbiafw/scabbia2-testing/unittests.php
  # - phpcs --standard=PSR2 --report=info .
  - output=$(phpcs --standard=PSR2 --report=emacs .); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;

matrix:
  allow_failures:
    - php: hhvm
